name: Deploy to Hostinger
  on:
    push:
      branches: [ master ]
  
  jobs:
  	deploy:
		  runs-on: biennale
  	steps:
  		- uses: actions/checkout@v5  
  		- name: Deploy to Hostinger
  	uses: hostinger/deploy-action@v1
  		with:
  			api-key: ${{ secrets.HOSTINGER_API_KEY }}
  			virtual-machine: ${{ vars.HOSTINGER_VM_ID }
