name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy-and-run:
    name: Deploy Biennale Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Transfer files to Hostinger via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.HOSTINGER_USERNAME }}/biennale"

      - name: Execute Docker Compose on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.HOSTINGER_USERNAME }}/biennale
            docker compose down
            docker compose up -d --build
